cinder: add boto3 dependency
cinder in master requires boto3 now, otherwise you get:

   File "/home/abuild/rpmbuild/BUILD/cinder-17.1.0.dev218/cinder/backup/drivers/s3.py", line 74, in <module>
     import boto3
   ModuleNotFoundError: No module named 'boto3'

Change-Id: I05f8c8458f13ab18e68b248689a513682ef50f38