oslo.policy: downgrade to 2.4.1
The version 3.0.0 causes all sphinx-build jobs to fail with errors
similar to this:

    oslo_config.cfg.ArgsAlreadyParsedError: arguments already parsed: cannot register CLI option

Thats why the 3.0.0 release is currently blacklisted in global u-c

Change-Id: I7de19da898f6962c40729bc908d2bc70f0267cfc