Fix check run for tooz
Previously no tests were run. Now set it up to
run at least the tests against memcached, extend
buildrequires accordingly, otherwise tests are failing with:

  File "/home/abuild/rpmbuild/BUILD/tooz-1.59.0/tooz/tests/__init__.py", line 20, in <module>
       import fixtures
  ImportError: No module named fixtures

Change-Id: Ie7fdbfecf9da06fdff5e04473f69f4117fd8e65f
(cherry picked from commit 752ff6aabe9fa40decb018134dc58ac2ad4f61b5)